-- MySQL Script generated by MySQL Workbench
-- Wed Dec 15 23:07:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`Item` (
  `idToDoList` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `desription` VARCHAR(300) NOT NULL,
  `targetTime` DATETIME NOT NULL,
  PRIMARY KEY (`idToDoList`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
